### ISSUE TITLE
Custom loss function - working example

### ISSUE THREAD

**Issue by rzietal** [dmlc/XGBoost.jl#101]
Hi, could you provide working example with meaningful comments on how to implement custom loss function? The example included in the tutorials doesn't work for me. It crashes with the following error

ERROR: LoadError: LoadError: MethodError: no method matching exp(::Vector{Float32})
Closest candidates are:
  exp(::StridedMatrix{var"#s832"} where var"#s832"<:Union{Float32, Float64, ComplexF32, ComplexF64}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/dense.jl:557
  exp(::StridedMatrix{var"#s832"} where var"#s832"<:Union{Integer, Complex{var"#s831"} where var"#s831"<:Integer}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/dense.jl:558
  exp(::LinearAlgebra.UniformScaling) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/uniformscaling.jl:174
  ...

What is the required type of the gradient and hessian to be returned by the custom loss function? Vector and matrix respectively, could please somebody shed some light on this?

Many thanks,
R.

**Comment by ablaom** [comment]
It looks like one needs to broadcast the `exp` at https://github.com/dmlc/XGBoost.jl/blob/14f93a1e91f8f6cc34666abe5e9780500ae31bef/demo/custom_objective.jl#L21

rather than apply directly to a vector. 

So replace the cited line with:

```julia
preds = 1.0 ./ (1.0 + exp.(-preds)) 
```

Does that fix the example for you?

**Comment by rzietal** [comment]
Hi,

I've tried that, then it crashes further down in XGBoosts eval_set with a type conversion error. What surprises me is that gradient and hessian are both returned as vectors (also in some other python examples I saw) Is hessian only meant to be the diagonal elements of it? Is this a universal property/requirement of a valid cost function to have vanishing off-diagonal elements of hessian?

Many thanks,
R.

**Comment by rzietal** [comment]
There is number of broadcasting fixes needed for logregobj to work. Correct code is below 

`function logregobj(preds::Vector{Float32}, dtrain::DMatrix)
    labels = get_info(dtrain, "label")
    preds = 1.0 ./ (1.0 .+ exp.(-preds))
    grad = preds - labels
    hess = preds .* (1.0 .- preds)
    return (grad, hess)
end`

With this the demo script works as expected. I must have had some conflicting xgboost settings, I cannot reproduce this crash any more.

**Comment by rzietal** [comment]
I have figured it out, there was a problem elsewhere in the code. Below is a complete example for implementation of the squared log loss as per python tutorial:

[https://xgboost.readthedocs.io/en/latest/tutorials/custom_metric_obj.html](url)

applied in a simple regression to fit a line

```julia
###
# advanced: cutomsized loss function
#

###
# train xgboost regressor with custom loss function
# implementation of squared log loss as per python tutorial
# https://xgboost.readthedocs.io/en/latest/tutorials/custom_metric_obj.html
#

###
# create fakey-fakey dataset - simple fit to a line for illustration purposes
# make sure y is greater then -1
line(x) = 0.5 * x + 4.3

x = 5 .+ 10*rand(100)
y = line.(x)

dtrain = DMatrix(reshape(x, length(x), 1); label = y)

x = 5 .+ 10*rand(10)
y = line.(x)
dtest = DMatrix(reshape(x, length(x), 1); label = y)

const objective = "reg:squarederror"         # Learning task / objective, set XGBoost to do multiclass classification using the softmax objective
const eta = 0.05                             # Learning rate - Step size shrinkage used in update to prevents overfitting
const gamma = 0.0                            # Minimum loss reduction required to make a further partition on a leaf node of the tree.
const max_depth = 8                          # Depth of the tree - larger makes model more complex and more likely to overfit.
const min_child_weight = 1                   # Minimum sum of instance weight (hessian) needed in a child.
const max_delta_step = 1                     # Maximum delta step we allow each leaf output to be.
const subsample = 1.0                        # Random sampling prior to tree growing
const colsample_bytree = 1                   # Subsample ratio of columns when constructing the tree, occurs on tree construct.
const lambda = 1                             # L2 Regularisation term on weights
const alpha = 0                              # L1 regularisation term on weights
const verbosity = 1                          # Valid values are 0 (silent), 1 (warning), 2 (info), 3 (debug)
const tree_method = "exact"
const trainingparams = Dict(
                            #"objective" => objective,
                            "eta" => eta,
                            "gamma" => gamma,
                            "max_depth" => max_depth,
                            "min_child_weight" => min_child_weight,
                            "max_delta_step" => max_delta_step,
                            "subsample" => subsample,
                            "colsample_bytree" => colsample_bytree,
                            "lambda" => lambda,
                            "alpha" => alpha,
                            "verbosity" => verbosity,
                            "tree_method" => tree_method,
                            )

watchlist  = [(dtest,"validation"), (dtrain,"trainining")]
num_round = 200

###
# squared log loss defined as 
loss(preds, labels) = 1/2 .* (log.(preds .+ 1.0) .- log.(label .+ 1.0))

###
# For the use as a custom loss in XGBoost we need to return gradient and hessian
# gradient is computed w.r.t. to the preds variable
function squared_log_loss(preds::Vector{Float32}, dtrain::DMatrix)::Tuple{Vector{Float32}, Vector{Float32}}

    labels = get_info(dtrain, "label")

    # predictions must be greater than -1
    preds = clamp.(preds, -1.0, typemax(Float32)) .+ eps(Float32)

    grad = (log.(preds .+ 1) .- log.(labels .+ 1)) ./ (1.0 .+ preds)
    hess = (1.0 .+ log.(labels .+ 1.0) .- log.(preds .+ 1.0) ) ./ (1.0 .+ preds).^2

    return (grad, hess)
end

function evalerror(preds::Vector{Float32}, dtrain::DMatrix)::Tuple{String, Float32}
    labels = get_info(dtrain, "label")
    # predictions must be greater than -1
    preds = clamp.(preds, -1.0, typemax(Float32)) .+ eps(Float32)
    eval = sum((log.(preds .+ 1.0) .- log.(labels .+ 1.0)).^2)/length(labels)
    return ("self-error", eval)
end

bst = xgboost(dtrain, num_round, param=trainingparams, watchlist=watchlist, obj=squared_log_loss, feval=evalerror)
```

**Comment by ExpandingMan** [comment]
An example using the new API is provided with the 2.0 docs.

This issue does not seem relevant any longer, if you disagree please comment or re-open.
