### ISSUE TITLE
How do I create persistent representations of learned parameters (models) ?

### ISSUE THREAD

**Issue by ablaom** [dmlc/XGBoost.jl#103]
The objects created by `xgboost` ("models") are not persistent (just some C pointers) and hence not serialisable. Working through the julia wrapper XGBoost.jl, the only way I know how to construct a persistent Julia representation of the model is to write to disk using `XGBoost.save` and then *read in* the file to a julia object (The MLJ serialiser does this [here](https://github.com/JuliaAI/MLJXGBoostInterface.jl/blob/9b50abccf6073c0f759d8d2119aef01f3a84fb48/src/MLJXGBoostInterface.jl#L688)). This is obviously not ideal. 

If someone knows how to *directly* get a persistent julia representation through the wrapper, or can suggest changes to this package that would allow this, then that would be great.

**Comment by ablaom** [comment]
cc @OlivierLabayle

**Comment by ExpandingMan** [comment]
I think what you're referring to here is the fact that, prior to 2.0, no Julia methods were provided to writing to an in-memory buffer.  The appropriate methods have been added and are now used in MLJXGBoostInterface.jl.

@ablaom , can you please clarify whether something else is being asked here, and if not close the issue?
