### ISSUE TITLE
DMatrix from DataFrame exampel in docs fails

### ISSUE THREAD

**Issue by SebastianCallh** [dmlc/XGBoost.jl#123]
Running the example

```julia
using DataFrames, XGBoost
df = DataFrame(randn(10,3), [:a, :b, :c])
dm = DMatrix(df)
XGBoost.getfeaturenames(dm) == ["a", "b", "c"]
```
from the documentation [here](https://github.com/dmlc/XGBoost.jl/blob/master/docs/src/index.md#feature-naming-and-tabular-data) gives the error

```
MethodError: no method matching DMatrix(::DataFrame)
Closest candidates are:
  DMatrix(::Matrix{<:Real}) at ~/.julia/packages/XGBoost/D30Xd/src/xgboost_lib.jl:45
  DMatrix(::Matrix{<:Real}, ::Bool) at ~/.julia/packages/XGBoost/D30Xd/src/xgboost_lib.jl:45
  DMatrix(::Matrix{<:Real}, ::Bool, ::Any; kwargs...) at ~/.julia/packages/XGBoost/D30Xd/src/xgboost_lib.jl:45
  ...
```
Unfortunate! Has support for DataFrame -> DMatrix been removed?
I'm using DataFrames v1.4.1 and XGBoost v1.5.2.

**Comment by tylerjthomas9** [comment]
The current version in the registry does not have `DMatrix` support. You will have to install from the current GitHub branch to use it. 

```julia
julia> using Pkg
julia> Pkg.add("https://github.com/dmlc/XGBoost.jl")
```

**Comment by SebastianCallh** [comment]
I see, thanks! I realize now I read the docs in the repo (i.e. on main) since the link in the readme 404s. Do you know if a new release with the aforementioned feature is planned soon?

**Comment by scheidan** [comment]
On version `2.0.0` the example from the docs still fails:
```Julia
using DataFrames
using XGBoost

df = DataFrame(randn(100,3), [:a, :b, :y])

# fails
bst = xgboost((df[!, [:a, :b]], df.y)) 

# work around
data = DMatrix(df[!, [:a, :b]], df.y)
bst = xgboost(data) # :)
```

I believe the reason is that the constructor for `Dmatrix` overly restrictive: 
```Julia
DMatrix(Xy::DataTuple; kw...) = DMatrix(Xy[1], Xy[2]; kw...)
```
Relaxing it to
```Julia
DMatrix(Xy::Tuple; kw...) = DMatrix(Xy[1], Xy[2]; kw...)
```
solves the issue.

**Comment by ExpandingMan** [comment]
This has been fixed, thanks to @tylerjthomas9 .
