### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by cstjean** [dmlc/XGBoost.jl#124]
The [link on the front page](https://dmlc.github.io/XGBoost.jl/) gives a 404

**Comment by ExpandingMan** [comment]
See the discussion [here](https://github.com/dmlc/XGBoost.jl/pull/121), we really need help from someone with admin rights on the package.

**Comment by hcho3** [comment]
I enabled the GitHub Pages feature on this repository.

**Comment by ExpandingMan** [comment]
Ah, nice!  Thanks to whoever fixed this!
