### ISSUE TITLE
[Community] Provide commit access to @ExpandingMan

### ISSUE THREAD

**Issue by aviks** [dmlc/XGBoost.jl#132]
@ExpandingMan has recently made significant improvements to the Julia package, [rewriting large parts of it](https://github.com/dmlc/XGBoost.jl/pull/111), and it would help for him to have commit access to this package. I'll continue to help maintain this package, but Michael is now much more conversant with this codebase, and xgboost in general. 

@tqchen @hcho3 would you consider this, please? Thanks!

**Comment by hcho3** [comment]
@aviks I sent an invitation to @ExpandingMan to obtain commit access to this repository.

**Comment by ExpandingMan** [comment]
Thank you.

I don't want to speak for him, so we should give him a chance to chime in, but I think it would also be good to grant this to @ablaom who is a prominent figure in the Julia machine learning community with a vested interest in maintaining this package.

**Comment by hcho3** [comment]
Sure, if @ablaom wants the commit access, I will send invitation as well.

**Comment by ablaom** [comment]
I'm spread too thin to take on any kind of maintenance responsibility, but I'm happy to have commit access as a back up. 

Wholeheartedly agree that adding @ExpandingMan is a good idea.

**Comment by tqchen** [comment]
Thank you @ExpandingMan ! no objections

**Comment by ExpandingMan** [comment]
Closing this as I have permissions.  Thanks all!
