### ISSUE TITLE
Github release out of date

### ISSUE THREAD

**Issue by Moelf** [dmlc/XGBoost.jl#137]
and documentation is not versioned, with breaking change this is un-usable for previous version

**Comment by ExpandingMan** [comment]
We've been trying to fix tagbot, but at this point I have no idea how to do that.  It probably requires intervention from people who have more permissions than I do.

**Comment by ablaom** [comment]
I'm not expert, but I do notice that the current [TagBot.yml](https://github.com/dmlc/XGBoost.jl/blob/master/.github/workflows/TagBot.yml) is missing a ssh key. (There is a `token`, but not `ssh`). See the bottom of this example from the TagBot docs:

```julia
name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      lookback:
        default: 3
permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Edit the following line to reflect the actual name of the GitHub Secret containing your private key
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          # ssh: ${{ secrets.NAME_OF_MY_SSH_PRIVATE_KEY_SECRET }}
```

So if this is added, and someone with privileges adds a corresponding secret key in the repo Settings, then maybe that will fix this....

**Comment by Moelf** [comment]
@aviks ?

**Comment by Moelf** [comment]
bump

**Comment by aviks** [comment]
@Moelf I now have as much privileges on this repo as @ExpandingMan. 

I do not think adding this key is necessary. I don't add this to any of my personal repos, and it seems to work. Here's and example from a couple of weeks ago: [Tagbot Run](https://github.com/aviks/GameZero.jl/actions/runs/3775848806), [Workflow file](https://github.com/aviks/GameZero.jl/blob/master/.github/workflows/tagbot.yml). You'll notice the run succeeded, and the workflow file does not have any ssh key defined. It only uses the default `GITHUB_TOKEN`

There have been long term reports about Tagbot being flakey in the past few months: https://github.com/JuliaRegistries/TagBot/issues/242

**Comment by aviks** [comment]
Also, it looks like the last Tagbot run succeeded, and `v2.2.1` has been successfully tagged: https://github.com/dmlc/XGBoost.jl/releases/tag/v2.2.1

**Comment by ExpandingMan** [comment]
Thanks for fixing.
