### ISSUE TITLE
removing info printed when using xgboost

### ISSUE THREAD

**Issue by mlesnoff** [dmlc/XGBoost.jl#151]
Is there a way to remove all the info printed when using xgboost?

The doc https://xgboost.readthedocs.io/en/stable/parameter.html indicates:

verbosity [default=1]
Verbosity of printing messages. Valid values are 0 (silent), 1 (warning), 2 (info), 3 (debug). Sometimes XGBoost tries to change configurations based on heuristics, which is displayed as warning message. If there’s unexpected behaviour, please try to increase value of verbosity.

But doing:

using XGBoost
(X, y) = (randn(100,4), randn(100))
bst = xgboost((X, y); verbosity = 0)

does not remove the printing. I also tried `verbosity = "0"` and `silent = "0"`, which does not work.

Is there a solution?

**Comment by ExpandingMan** [comment]
You need to also set `watchlist=(;)` (or some other empty collection)

**Comment by mlesnoff** [comment]
bst = xgboost((X, y), watchlist = (;)) ;

this works, thanks!
