### ISSUE TITLE
Processing restricted to a single thread

### ISSUE THREAD

**Issue by slundberg** [dmlc/XGBoost.jl#17]
This may not be specific to Julia, but when I work with XGBoost.jl models in memory, I often see the performance drop from ~3600% CPU usage to 100% next time I train. No errors are given, and there is plenty of RAM and CPU available.

Any ideas why this might be occurring? The only solution I have right now is to restart my whole session.

**Comment by maximsch2** [comment]
Do you break it in the middle of the training session by any chance (if you are doing it interactively from IJulia)? I saw this happen for me in those cases, maybe OpenMP is being stuck in some weird state?

**Comment by slundberg** [comment]
Good point. I was working in an interactive session, but couldn't reproduce
it consistently so I don't know if it was restricted to times when I
interrupted the training.

**Comment by slundberg** [comment]
Closing this since it is likely not an issue with the Julia interface.
