### ISSUE TITLE
Update term.jl dependency

### ISSUE THREAD

**Issue by Roh-codeur** [dmlc/XGBoost.jl#173]
hi

thanks for all the work on this lib. Looks like Term.jl was upgraded to 2.0. I was updating packages and it appears that XGBoost is dependent on Term@1. Is it possible to upgrade Term.jl to 2.0 please?

many thanks
Roh

**Comment by ExpandingMan** [comment]
#174

**Comment by Roh-codeur** [comment]
@ExpandingMan : you, my friend, are awesome!

**Comment by ExpandingMan** [comment]
Getting downgrades or stuck packages in one of my pet peaves.  Drives me crazy.
