### ISSUE TITLE
nfold_cv doesn't work

### ISSUE THREAD

**Issue by skondrat** [dmlc/XGBoost.jl#21]
When I tried out some code from demo:

dtrain = DMatrix("agaricus.txt.train")
param = ["max_depth"=>2, "eta"=>1, "silent"=>1, "objective"=>"binary:logistic"]
num_round = 2
nfold = 5

xgboost(dtrain, num_round, param = param, metrics=["error"], seed = 0) #this works
nfold_cv(dtrain, num_round, nfold, param = param, metrics=["error"], seed = 0) #this doesn't

**I got this error:
**MethodError: `isless` has no method matching isless(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  isless(!Matched::DataArrays.NAtype, ::Any)
  isless(::Any, !Matched::DataArrays.NAtype)
 in sort! at sort.jl:221
 in sort! at sort.jl:310
 in sort! at sort.jl:402
 in aggcv at /Users/skondrat/.julia/v0.4/XGBoost/src/xgboost_lib.jl:284
 in nfold_cv at /Users/skondrat/.julia/v0.4/XGBoost/src/xgboost_lib.jl:307
 in include_string at /Users/skondrat/.julia/v0.4/CodeTools/src/eval.jl:28
 in include_string at /Users/skondrat/.julia/v0.4/CodeTools/src/eval.jl:32
 [inlined code] from /Users/skondrat/.julia/v0.4/Atom/src/eval.jl:39
 in anonymous at /Users/skondrat/.julia/v0.4/Atom/src/eval.jl:62
 in withpath at /Users/skondrat/.julia/v0.4/Requires/src/require.jl:37
 in withpath at /Users/skondrat/.julia/v0.4/Atom/src/eval.jl:53
 [inlined code] from /Users/skondrat/.julia/v0.4/Atom/src/eval.jl:61
 in anonymous at task.jl:58

**Comment by slundberg** [comment]
#20 fixes this. So this can be closed.
