### ISSUE TITLE
Wrapper functions use UInt64 instead of UInt32

### ISSUE THREAD

**Issue by Allardvm** [dmlc/XGBoost.jl#24]
It looks like the functions in [xgboost_wrapper_h.jl](https://github.com/dmlc/XGBoost.jl/blob/master/src/xgboost_wrapper_h.jl) erroneously expect XGBoost's library to return results as `UInt64`, while they actually return the equivalent of Julia's `UInt32`. The result is that these functions return the wrong values.

Take the example of [XGDMatrixNumRow()](https://github.com/dmlc/XGBoost.jl/blob/master/src/xgboost_wrapper_h.jl#L126-L134), which expects XGBoost's output to be stored in a reference to a `UInt64`.

``` julia
function XGDMatrixNumRow(handle::Ptr{Void})
    ret = Ref{UInt64}()
    @xgboost_ccall(
        :XGDMatrixNumRow,
        (Ptr{Void}, Ref{UInt64}),
         handle, ret
    )
    return ret[]
end
```

If we take a loot at XGBoost's [c_api.cc:451-456](https://github.com/dmlc/xgboost/blob/master/src/c_api/c_api.cc#L451-L456), we find that it expects a pointer to a `bst_ulong` and second argument:

``` cc
int XGDMatrixNumRow(const DMatrixHandle handle,
                    bst_ulong *out) {
  API_BEGIN();
  *out = static_cast<bst_ulong>(static_cast<const DMatrix*>(handle)->info().num_row);
  API_END();
}
```

In XGBoost's [c_api.h:26](http://github.com/dmlc/xgboost/blob/master/include/xgboost/c_api.h#L26), we find that `bst_ulong` is defined as an `unsigned long`. As far as I know, Julia's equivalent to this is an `UInt32`, not an `UInt64`.

``` h
// manually define unsign long
typedef unsigned long bst_ulong;  // NOLINT(*)
```

This frequently causes errors when Julia previously stored large arrays that were subsequently freed, which causes it to reuse memory. Since calls to `Ref{UInt64}()` do not zero out the memory, it is not guarateed to be zero. In this case, the call to `XGDMatrixNumRow()` will store valid data in the 32 bit part of the `UInt64`, but leave whatever value was in the remainder intact. The result is that it sometimes erroneously reports the number of rows.

I can replicate this by calling `XGBoost.XGDMatrixNumRow(trainer.handle)` a few times in a Julia session that has previously been used to store and release a large number of sizable arrays. The call usually returns:

``` julia
XGBoost.XGDMatrixNumRow(trainer.handle)
0x00000000000007d0
```

But sometimes (notice that the 32bit portion of the `UInt32` is still correct):

``` julia
XGBoost.XGDMatrixNumRow(trainer.handle)
0x3feff5f2000007d0
```

**Comment by maximsch2** [comment]
Are you using Windows by any chance? This: https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models seems to indicate, that `unsigned long` should be 64 bit everywhere except on Windows. XGBoost should be using something like `int64_t` there to be more portable.

**Comment by Allardvm** [comment]
Yes, this was on a Windows machine. Perhaps we could define the correct size somewhere for each platform somewhere in the package?

**Comment by Allardvm** [comment]
I finally got around to sorting this out the proper way—with Julia's system independent c types. In the meantime, XGBoost's C API has changed its definition of `bst_ulong`, but the Julia package still builds against an older version that has this issue.

I'd be happy to submit a pull request from my fork (https://github.com/Allardvm/XGBoost.jl) that uses Julia's portable c types everywhere.

**Comment by slundberg** [comment]
A PR sounds great! I have been meaning to update the Julia binding to match the latest XGBoost but have not done anything on it. It looks like you are linking against master right?

**Comment by Allardvm** [comment]
Yes, my fork builds against the XGBoost master because I'm using the new histograms. The Julia package should probably build a stable version though, but I could check if any of the C API have changed in the meantime. If not, I could provide an interface that allows users to specify their own XGBoost library.

There are some other fixes in the fork as well—so far mostly small changes that change some of the Python-inspired code to what Julia users might expect. I'll also make sure the library can precompile before submitting the PR.

**Comment by slundberg** [comment]
Great! By default I think it should build the most recent stable version,
but providing a switch to make it easier build against master seems like a
good idea to me.

**Comment by Allardvm** [comment]
The latest stable version has slightly different typedefs from the latest master, so it'll take a bit more work than expected. I'll adapt the fork to use `ENV["XGBOOST_BUILD_VERSION"]` to indicate the version to build, with missing (default) indicating "the latest stable version". The build process will add a global const to the library-loading code that indicates the library version (since this functionality isn't available in the library itself), which is used in the wrapper to set the appropriate typedefs.
