### ISSUE TITLE
Build errors in Julia 0.3.8

### ISSUE THREAD

**Issue by theiling** [dmlc/XGBoost.jl#3]
I tried to add XGBoost.jl to Julia and hot build errors.

Pkg.add("XGBoost")
.. none of the available packages can install dependcy xgboostwrapper
WARNING: XGBoost had build errors

i tried also 
Pkg.clone("https://github.com/antinucleon/XGBoost.jl.git")
 Pkg.build("XGBoost")

Same result.

Any Ideas?

ye the way: This is th eoutput from Pkg.clone/Pkg.build
julia> Pkg.clone("https://github.com/antinucleon/XGBoost.jl.git")
INFO: Cloning XGBoost from https://github.com/antinucleon/XGBoost.jl.git
INFO: Computing changes...
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.build("XGBoost")
INFO: Building XGBoost
===============================[ ERROR: XGBoost ]===============================

None of the selected providers can install dependency xgboostwrapper.
Use BinDeps.debug(package_name) to see available providers

while loading C:\dev\WinPython-64bit-3.4.3.2FlavorJulia\settings.julia\v0.3\XGB
oost\deps\build.jl, in expression starting on line 24
# 

================================[ BUILD ERRORS ]================================

WARNING: XGBoost had build errors.
- packages with build errors remain installed in C:\dev\WinPython-64bit-3.4.3.2
  FlavorJulia\settings.julia\v0.3
- build the package(s) and all dependencies with `Pkg.build("XGBoost")`
- build a single package by running its `deps/build.jl` script
# 

julia> BinDeps.debug("xgboostwrapper")
INFO: Reading build script...
ERROR: could not open file C:\dev\WinPython-64bit-3.4.3.2FlavorJulia\settings.j
ulia\v0.3\xgboostwrapper\deps\build.jl
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in debug_context at C:\dev\WinPython-64bit-3.4.3.2FlavorJulia\settings.julia\v
0.3\BinDeps\src\debug.jl:54
 in debug at C:\dev\WinPython-64bit-3.4.3.2FlavorJulia\settings.julia\v0.3\BinD
eps\src\debug.jl:59
 in debug at C:\dev\WinPython-64bit-3.4.3.2FlavorJulia\settings.julia\v0.3\BinD
eps\src\debug.jl:65

**Comment by antinucleon** [comment]
Thanks for letting me know. I will check it late today since xgboost changes a lot recently.

**Comment by tristanmarkwell** [comment]
FYI, getting the same error in Julia 0.4.0 rc 1 (as well as a warning about the deprecated dictionary syntax).

**Comment by antinucleon** [comment]
Sorry I am still working on https://github.com/dmlc/mxnet . I will refactor this project once I finish all work there.

**Comment by cybertaurean** [comment]
Was this resolved? I'm still getting this error while trying to build XGBoost in julia.

**Comment by zhmz90** [comment]
@cybertaurean  have you tried  building XGBoost on Julia v0.4 or v0.5 since Julia v0.3 is a little old?

**Comment by cybertaurean** [comment]
@zhmz90 I tried building on Julia v0.4 - Following is what I get as output -
```
C:\Users\cyber\.julia\v0.4>julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.clone("https://github.com/antinucleon/XGBoost.jl.git")
INFO: Cloning XGBoost from https://github.com/antinucleon/XGBoost.jl.git
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.build("XGBoost")
INFO: Building XGBoost
===============================[ ERROR: XGBoost ]===============================

LoadError: None of the selected providers can install dependency xgboostwrapper.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\cyber\.julia\v0.4\XGBoost\deps\build.jl, in expression starting on line 24

================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: XGBoost had build errors.

 - packages with build errors remain installed in C:\Users\cyber\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("XGBoost")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================
```

**Comment by cybertaurean** [comment]
The deps/build.jl has the following -
```
C:\Users\cyber\.julia\v0.4\XGBoost\deps>type build.jl
using BinDeps
@BinDeps.setup

deps = [ libxgboostwrapper = library_dependency("xgboostwrapper", aliases = ["libxgboostwrapper.so"]) ]

prefix=joinpath(BinDeps.depsdir(libxgboostwrapper),"usr")
provides(BuildProcess,
           (@build_steps begin
               `rm -rf xgboost`
               `git clone https://github.com/dmlc/xgboost.git --recursive`
               CreateDirectory(prefix)
               CreateDirectory(joinpath(prefix, "lib"))
               @build_steps begin
                   ChangeDirectory("xgboost")
                   FileRule(joinpath(prefix,"lib","libxgboostwrapper.so"), @build_steps begin
                       `git checkout 0.47` # v0.40
                       `bash build.sh`
                       `cp wrapper/libxgboostwrapper.so $prefix/lib`
                   end)
               end
            end),
         libxgboostwrapper)

@BinDeps.install Dict(:xgboostwrapper => :_xgboost)
```

**Comment by cybertaurean** [comment]
```
julia> BinDeps.debug("XGBoost")
INFO: Reading build script...
The package declares 1 dependencies.
 - Library "xgboostwrapper"
    - Providers:
      - Simple Build Process
```

**Comment by zhmz90** [comment]
I just find out your OS is Windows. This package's default building process only support Linux. I will try to add support on OSX and windows. But now you need build shared library of xgboost manually and set `XGBoost._xgboost` to its location.  [How to build xgboost on windows](https://xgboost.readthedocs.io/en/latest/build.html#building-on-windows) may be helpful to you.

**Comment by cybertaurean** [comment]
@zhmz90 Thank you so much. I had built libxgboost.dll using MinGW (it failed initially with VS, and I read that the support to VS was removed). I was able to incorporate the library for Python. However, how do I incorporate libxgboost.dll to Julia? I'm pretty new to Julia and would appreciate if you could help out with getting this working on Julia (it's working on Python for me).

**Comment by zhmz90** [comment]
Try to replace the line `include("../deps/deps.jl")` in `joinpath(Pkg.dir("XGBoost"), src/xgboost_wrapper_h.h)` with `const _xgboost = full_path_of_your_libxgboost.dll`

**Comment by cybertaurean** [comment]
@zhmz90 I changed xgboost_wrapper_h.jl to the following -

```
#include("../deps/deps.jl")
const _xgboost = "C:\Users\cyber\.julia\v0.4\XGBoost\src\libxgboost.dll"
```

However, the process is still failing in deps/build.jl with the same error as before -

```
LoadError: None of the selected providers can install dependency xgboostwrapper.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\cyber\.julia\v0.4\XGBoost\deps\build.jl, in expression starting on line 24
```

**Comment by zhmz90** [comment]
@cybertaurean, you don't need to run `Pkg.build("XGBoost")`, just directly use this package with `using XGBoost`.

**Comment by cybertaurean** [comment]
@zhmz90 I will run the module and come back with questions (if any). Appreciate the help.

**Comment by cybertaurean** [comment]
@zhmz90 It still doesn't seem to get the reference to libxgboost.dll and fails at xgboost --> makeDMatrix --> DMatrix --> XGDMatrixCreateFromMatT (error message below) -

```
LoadError: error compiling __call#177__: error compiling XGDMatrixCreateFromMatT: could not load library ".libxgboost.dll"
The specified module could not be found.

while loading In[14], in expression starting on line 1
```

I still have the fully qualified path of the dll added to the xgboost_wrapper_h.jl file.

```
#include("../deps/deps.jl")
const _xgboost = "C:\Users\cyber\.julia\v0.4\XGBoost\src\libxgboost.dll"
# xgboost_wrapper.h
```

**Comment by zhmz90** [comment]
@cybertaurean, Could you give me a more detailed stack trace message?

**Comment by cybertaurean** [comment]
@zhmz90 That's all I'm seeing when I try to call xgboost module. I went into the modules and traced the call to where it was failing. Is there any particular detail that you are looking for?

**Comment by maximsch2** [comment]
Have you built the latest version of the XGBoost or the one from the branch that is used by XGBoost.jl? You should do `git checkout 0.47` inside your XGBoost repo before building the library.

**Comment by danielgrossma** [comment]
I ran into the exact same issue as cybertaurian: 

"error compiling XGDMatrixCreateFromMatT: could not load library ".libxgboost.dll"
The specified module could not be found."

Trying out:

git checkout 0.47

before building the shared lib resulted in a failure to compile. Do you have a more detailed explanation on how it should be done?

I'm running on Windows 10

**Comment by peemblis** [comment]
I'm having the same errors with Julia 0.4.6 as the opening post. I'm on Windows 7.

--------------------------------------------

**julia> Pkg.add("XGBoost")**
_INFO: Cloning cache of XGBoost from git://github.com/dmlc/XGBoost.jl.git
INFO: Installing XGBoost v0.2.0
INFO: Building XGBoost
===============================[ ERROR: XGBoost ]===============================

LoadError: None of the selected providers can install dependency xgboostwrapper.
Use BinDeps.debug(package_name) to see available providers

while loading ...\.julia\v0.4\XGBoost\deps\build.jl, in expression starting on line 24

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: XGBoost had build errors.

 - packages with build errors remain installed in ...\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("XGBoost")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of XGBoost
INFO: Use `Pkg.update()` to get the latest versions of your packages_

**julia> Pkg.build("XGBoost")**
_===============================[ ERROR: XGBoost ]===============================

LoadError: None of the selected providers can install dependency xgboostwrapper.
Use BinDeps.debug(package_name) to see available providers

while loading ...\.julia\v0.4\XGBoost\deps\build.jl, in expression starting on line 24

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: XGBoost had build errors.

 - packages with build errors remain installed in ...\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("XGBoost")`
 - build a single package by running its `deps/build.jl` script

================================================================================_

**Comment by slundberg** [comment]
I don't have access to a windows machine, so I can't be of much assistance. However there is nothing special about building XGBoost for Julia vs. building it standalone. The commands are:

```bash
git clone https://github.com/dmlc/xgboost.git --recursive
cd xgboost
git checkout 0.47
bash build.sh
cp wrapper/libxgboostwrapper.so SOME_INSTALL_LOCATION
```

I would recommend just getting those commands to work before worrying about the Julia package part of XGBoost.

**Comment by maximsch2** [comment]
I think you are supposed to build XGBoost through Visual Studio on Windows, not through bash script. It is a bit painful, but doable. I remember also seeing pre-built binaries for Windows, you can try looking for them.

**Comment by elichow** [comment]
Hi, I'm trying to build XGBoost for Julia 0.4.6 on Windows, but I keep getting the same build error above. I already built the dmlc xgboost for python 3 with git bash, but I don't know how to do it for Julia.

Does anyone know a way to do it?
Thx

**Comment by yose6** [comment]
Hi, I'm trying to build XGBoost for Julia 0.4.6 on Windows, but I keep getting the same build error above. I already built the dmlc xgboost for python 3 (anaconda), but I don't know how to do it for Julia XGBoost.jl

Does anyone know a way to do it?
Thx

**Comment by ChrisRackauckas** [comment]
I think this issue is more about Windows than the Julia version. I opened an issue here:

https://github.com/dmlc/XGBoost.jl/issues/51

and in there I show how you can get it to work on Windows. That could probably be used to build a solution.

**Comment by ViralBShah** [comment]
Close?
