### ISSUE TITLE
Inconsistency between sparse and dense inputs

### ISSUE THREAD

**Issue by slundberg** [dmlc/XGBoost.jl#32]
It seems as though models trained on dense data cannot predict using sparse matrices:

```julia
using XGBoost

srand(1)
X = randn(1000,10)
X .*= randbool(size(X)...)
y = randn(1000)
m = xgboost(X, 2, label=y, silent=2)
println("diff with sparse(X) = ", norm(predict(m, X) .- predict(m, sparse(X))))
println("diff with full(sparse(X)) = ", norm(predict(m, X) .- predict(m, full(sparse(X)))))
```

produces

```
diff with sparse(X) = 12.708112
diff with full(sparse(X)) = 0.0
```

I am looking into it, but want to note the issue here for now.

**Comment by tqchen** [comment]
mainly on the definition of missing value. XGBoost treat the non-presenting entries as missing. For dense matrix, 0 is not treated as missing.

**Comment by slundberg** [comment]
Got it, thanks!
