### ISSUE TITLE
How to treat missing values

### ISSUE THREAD

**Issue by abhijithch** [dmlc/XGBoost.jl#33]
I was trying the Julia version of the Kaggle-Higgs code, and when I do `xgmat = DMatrix( data, label=label, missing=-999.0)` I get an `_setinfo has no method matching _setinfo(::Ptr{Void}, ::ASCIIString, ::Float64)` error. But in the implementation of `DMatrix()` function I see that we can pass the `missing` parameter. Can you please let me know how are we supposed to pass the `data`? Thanks.

**Comment by abhijithch** [comment]
@tqchen sorry to bother you, do you have any way I can get around this. I might not be using the `DMatrix` function the right way. I just need to run your [higgs example](https://github.com/dmlc/xgboost/blob/master/demo/kaggle-higgs/higgs-numpy.py). I tried a hack way of replacing zeros with `eps()` and making the `-999.0` to zeros, then convert this to a sparse matrix and pass to `DMatrix`, but this definitely did not work.

**Comment by slundberg** [comment]
`missing` is a positional argument and not a keyword argument (which you are using it as), that is likely part of the problem.
