### ISSUE TITLE
Discuss package refactoring and the road to feature parity

### ISSUE THREAD

**Issue by Allardvm** [dmlc/XGBoost.jl#37]
I'm currently refactoring the internals of this package to make optimal use of the Julia language and I keep running into the same trade-off, and I'd like some input.

On the one hand, we can keep the package as close as possible to the Python package (as it is now). This makes it quite easy for new users to get started, since they might be familiar with the Python package. Even if they aren't, they can rely on the Python documentation. Nevertheless, the current Julia interface differs in some respects; functions have different names, arguments have a different order, and some functions are not (yet) supported. A refactoring of the `update()` function in this style would look something like:

```julia
function update(bst::Booster, dtrain::DMatrix, iteration::Integer;
                fobj::Union{Function,Void} = nothing)
    if typeof(fobj) == Function
        pred = predict(bst, dtrain)
        grad, hess = fobj(pred, dtrain)
        @assert size(grad) == size(hess)
        XGBoosterBoostOneIter(bst.handle, dtrain.handle, grad, hess, length(hess))
    else
        XGBoosterUpdateOneIter(bst.handle, iteration, dtrain.handle)
    end
end
```

On the other hand, it is important to use a coding style that'll be familiar to other Julia users. This avoids errors (such as users not recognizing that an argument is keyword argument), makes it more likely that we'll attract contributions, and more likely that users spot a bug. There is also some performance to be gained by doing this. Keyword arguments, for example, are not accounted for in Julia's multiple dispatch, and can lead to type-instability. For this kind of package, the performance loss will not be too severe when fitting large models, but the performance penalty can be noticeably when evaluating a large number of small models. A refactor in this style that uses multiple dispatch would look something like:
```julia
function update(bst::Booster, dtrain::DMatrix, iteration::Integer)
    XGBoosterUpdateOneIter(bst.handle, iteration, dtrain.handle)
end

function update(bst::Booster, dtrain::DMatrix, iteration::Integer, fobj::Function)
    pred = predict(bst, dtrain)
    grad, hess = fobj(pred, dtrain)
    @assert size(grad) == size(hess)
    XGBoosterBoostOneIter(bst.handle, dtrain.handle, grad, hess, length(hess))
end
```

In addition to these considerations, there is the issue of breaking compatibility with previous versions. There are some functions, such as `xgboost()`, that have an unconventional name and are also not available in other XGBoost libraries (which use `train()`). I'd say we should rename these functions, because this increases cross-language consistency regardless of the coding style that we adopt. What do you think?

**Comment by slundberg** [comment]
Good questions. My first reaction is that consistency with the Python API would be helpful for the XGBoost community in general because examples people find in one language map more easily to another. The performance hit for small models from keyword args seems like an edge case to me. If someone is that concerned with the function call overhead they could write their own `update()`.

I agree that changing the names (such as `xgboost` to `train`) to match other libraries is a good idea.

Thanks for working on the much needed update :)

**Comment by Allardvm** [comment]
Thanks for the input. For the current use-case, I don't think multiple dispatch will result in more easily interpretable code. There'll be less conditionals in the methods, but there will also be more more methods with similar functionality. I'm inclined to agree with you that it would be wise to stick to the Python API. In the end, the refactor will then have the same function names, argument order, and use of keywords. 

I'll submit a PR once I've made some progress. Leaving this issue open for now so more people to chime in if they want.

**Comment by slundberg** [comment]
Once this gets merged I think we should release a new version to capture all the new updates for users not cloning the repo.

**Comment by Allardvm** [comment]
Closing this since we can continue the discussion in https://github.com/dmlc/XGBoost.jl/pull/44.
