### ISSUE TITLE
Missing XGBoost parameters when calling nfold_cv

### ISSUE THREAD

**Issue by dmitrijsc** [dmlc/XGBoost.jl#40]
Hi guys,

I've just started using Julia and noticed XGBoost is missing some parameters.
Any plans to implement early_stopping_rounds and print_every_n rows in the next version when doing nfold_cv? 

I have started writing my own implementation to fix the issues but it would be great if it is available out of the box.

**Comment by slundberg** [comment]
Not that I know of, but PR's are welcome. Though you should check with @Allardvm since he was working on a refactor that would effect this last I know.

**Comment by dmitrijsc** [comment]
Thanks for your answer. I will get in touch with him a little bit later.
