### ISSUE TITLE
nfold_cv returns

### ISSUE THREAD

**Issue by AStupidBear** [dmlc/XGBoost.jl#41]
I think nfold_cv should also return the computed statistics, not `nothing`, like the Python API

![2017-03-20_095609](https://cloud.githubusercontent.com/assets/16422976/24086961/74607562-0d53-11e7-8070-9b073705273b.jpg)

**Comment by dmitrijsc** [comment]
I think we should merge this with https://github.com/dmlc/XGBoost.jl/issues/40

I have done some minor change to the package on your question and will share the code when it is clean and tidy.

**Comment by AStupidBear** [comment]
I think I'll move to Python API of xgboost.
