### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by andreasnoack** [dmlc/XGBoost.jl#50]
Would be great if you could tag a new release since the current released version doesn't load on Julia 0.6.

**Comment by slundberg** [comment]
I'll work on that here shortly.

**Comment by rakeshvar** [comment]
Can we get a new release tag for Julia 0.6. (As julia 0.7, 1.0 are much more work and we can work with .6 in the interim?) Thanks.

**Comment by ViralBShah** [comment]
Can probably close this.
