### ISSUE TITLE
Don't work for Julia1.0

### ISSUE THREAD

**Issue by dmitrypenzar1996** [dmlc/XGBoost.jl#52]
Installation fails with the following error:
┌ Error: Error building `XGBoost`: 
│ ERROR: LoadError: syntax: misplaced assignment statement in "[libxgboostwrapper = library_dependency("xgboostwrapper", aliases = ["libxgboostwrapper.so"])]"
│ Stacktrace:
│  [1] include at ./boot.jl:317 [inlined]
│  [2] include_relative(::Module, ::String) at ./loading.jl:1038
│  [3] include(::Module, ::String) at ./sysimg.jl:29
│  [4] include(::String) at ./client.jl:388
│  [5] top-level scope at none:0
│ in expression starting at /Users/dmitrypenzar/.julia/packages/XGBoost/ZDo2d/deps/build.jl:4
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

**Comment by slundberg** [comment]
Thanks, this needs cleaned up and released for 1.0. I'll do it if I get a chance, otherwise PRs are welcome :)

**Comment by ViralBShah** [comment]
Builds fine on mac right now.
