### ISSUE TITLE
compilation error on win 10 julia 0.7

### ISSUE THREAD

**Issue by ajaychat3** [dmlc/XGBoost.jl#53]
julia> Pkg.build("XGBoost")
  Building XGBoost → `C:\Users\chatura\.julia\dev\XGBoost\deps\build.log`
 Resolving package versions...
┌ Error: Error building `XGBoost`:
│ [ Info: Using the latest master version of the XGBoost library
│ ERROR: LoadError: None of the selected providers can install dependency xgboost.
│ Use BinDeps.debug(package_name) to see available providers
│
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\chatura\.julia\packages\BinDeps\ZEval\src\dependencies.jl:949
│  [3] satisfy!(::BinDeps.LibraryDependency) at C:\Users\chatura\.julia\packages\BinDeps\ZEval\src\dependencies.jl:922
│  [4] top-level scope at C:\Users\chatura\.julia\packages\BinDeps\ZEval\src\dependencies.jl:977
│  [5] include at .\boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1038
│  [7] include(::Module, ::String) at .\sysimg.jl:29
│  [8] include(::String) at .\client.jl:398
│  [9] top-level scope at none:0
│ in expression starting at C:\Users\chatura\.julia\dev\XGBoost\deps\build.jl:36
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068

**Comment by ViralBShah** [comment]
Closing in favour of #53
