### ISSUE TITLE
Use BinaryBuilder to provide pre-built XGBoost binaries

### ISSUE THREAD

**Issue by ViralBShah** [dmlc/XGBoost.jl#61]
It would be nice to use BinaryBuilder / BinaryProvider for the xgboost binaries.

@staticfloat Is this something we should do in Yggdrasil itself? 

cc @aviks

**Comment by ViralBShah** [comment]
Related discussion: #51

**Comment by ViralBShah** [comment]
Filed upstream in https://github.com/JuliaPackaging/Yggdrasil/issues/10

**Comment by aviks** [comment]
Fixed by #68
