### ISSUE TITLE
[COMMUNITY] Provide commit access to a few Julia regulars?

### ISSUE THREAD

**Issue by ViralBShah** [dmlc/XGBoost.jl#64]
Hello @slundberg  

I think some of us in the Julia community could help out with this package and its maintenance and curating the issues. Would it be possible to give commit access to some folks?

Maybe @viralbshah, @aviks, and @dhairyagandhi96 to start with?

**Comment by slundberg** [comment]
That would be great! I started helping with this when I was using the Julia API a while back, but have since been consumed with just keeping up with my own repos. @tqchen or @hcho3 do you know how best to add folks for XGBoost.jl ? I don't seem to have access to manage members/access directly.

**Comment by aviks** [comment]
Thanks, @tqchen!

**Comment by tqchen** [comment]
Thanks @ViralBShah. Ideally, We bring active contributors as committers of the XGBoost community. Given that we also operate on trust and I do think it is best to get the folks on board as early as possible, I give you along with other friends temporary commit access. 

After a while, @hcho3 and XGBoost PMC can revisit and bring you formally as committer

**Comment by ViralBShah** [comment]
Thanks @tqchen
