### ISSUE TITLE
Custom verbosity

### ISSUE THREAD

**Issue by ErwanPiR** [dmlc/XGBoost.jl#71]
Hi,

I haven't find out how to change verbosity in the xgboost call.
And the print
```
[1] train-rmse:1.2
[2] train-rmse:1.3
```
is quite annoying when you launch multiple runs.

Is there something I miss to adjust the verbosity ?

Thanks for your help.

**Comment by ablaom** [comment]
I believe `silent=true` works.

**Comment by ErwanPiR** [comment]
Excellent ! Thanks @ablaom, it's what I was looking for !
