### ISSUE TITLE
how to get the trees

### ISSUE THREAD

**Issue by smith4455** [dmlc/XGBoost.jl#72]
Hi, 

I am trying to get the prediction values of each tree from XGBoost model, to find the standard deviation of the results. Since xgboost only gives me one prediction, I don't have access to that. 

I tried 
```
dump_model(bst, “dump.raw.txt”)
# If you have feature map file, you can dump the model in a more readable way
dump_model(bst, “dump.nice.txt”, fmap = joinpath(DATAPATH, “featmap.txt”))
```

to get the individual trees. But I don't know how to load them to use in Julia.

Thank you for your help
Ali

**Comment by ExpandingMan** [comment]
Now possible in 2.0
