### ISSUE TITLE
Can't set DMatrix attributes in Julia

### ISSUE THREAD

**Issue by compleathorseplayer** [dmlc/XGBoost.jl#75]
I urgently need to be able to set and access attibutes in Julia, like I have been used to doing in R.

In R, after I have defined a DMatrix object (say, 'dtrain')  all I have to do is:

attr(dtrain, "myparam") = value

And then to retrieve this (e.g. within a customised objective function) I use:

myparam = attr(dtrain, "myparam")

and the assigned value(s) will be loaded into myparam .

I have tried everything in Julia, but I can't seem to achieve the same thing
in a way which is compatible with XGBoost.  I can't seem to find
any documentation or examples relating to this anywhere.

I would be grateful for any help.

**Comment by ExpandingMan** [comment]
This was likely possible but poorly documented before 2.0, now it should be both possible and documented.
