### ISSUE TITLE
Missing tags for versions 0.4.3 and 1.1.1

### ISSUE THREAD

**Issue by omus** [dmlc/XGBoost.jl#91]
These [versions are registered](https://github.com/JuliaRegistries/General/blob/master/X/XGBoost/Versions.toml) but no tags exist here.

**Comment by aviks** [comment]
Tagbot is running on this repo, so I wonder why the tags are missing. I'll note that the releases were made with the web registrator -- is that significant? Might be worthwhile paging @christopher-dG -- help!

**Comment by christopher-dG** [comment]
@aviks the TagBot action was added to this repo after the last two releases were made, so it didn't pick them up (it only looks a couple of days into the past). You can get those tags in by [running TagBot manually](https://github.com/JuliaRegistries/TagBot#local-usage).

```sh
$ docker run --rm degraafc/tagbot python -m tagbot.local \
    --repo dmlc/XGBoost.jl \
    --token <TOKEN> \
    --version v0.4.3

$ docker run --rm degraafc/tagbot python -m tagbot.local \
    --repo dmlc/XGBoost.jl \
    --token <TOKEN> \
    --version v1.1.1
```

**Comment by aviks** [comment]
This is now done. Thanks Chris for the pointer.
