### ISSUE TITLE
Verbosity=0  not working?

### ISSUE THREAD

**Issue by mlesnoff** [dmlc/XGBoost.jl#98]
Hello, I am using function xgboost of XGboost.jl. It seems that argument 'verbosity = 0' does not make 100% silent returns (there are printing messages anyway).  

`n = 50 ; p = 5 ;
X = rand(n, p) ; y = rand(n) ;
num_round = 3 ;
fm = xgboost(X, num_round; label = y, max_depth = 2, verbosity = 0)`

Printing messages:

`[1]     train-rmse:0.280325
[2]     train-rmse:0.266210
[3]     train-rmse:0.255710
Booster(Ptr{Nothing} @0x000000001ecf3ea0)`

Is there a way to get a 100% silent return?

**Comment by rcurtin** [comment]
It seems like the `silent=true` option might help here (see #71); that worked at least partially for me, although I still have not managed to filter out things like:

```
[13:41:25] INFO: /workspace/srcdir/xgboost/src/tree/updater_prune.cc:101: tree pruning end, 12 extra nodes, 0 pruned nodes, max_depth=3
```

**Comment by mlesnoff** [comment]
perfect, that works for me, many thanks @rcurtin
